export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS";
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const USER_UPDATE_PROFILE_REQUEST = "USER_UPDATE_PROFILE_REQUEST";
export const USER_UPDATE_PROFILE_SUCCESS = "USER_UPDATE_PROFILE_SUCCESS";
export const USER_UPDATE_PROFILE_FAIL = "USER_UPDATE_PROFILE_FAIL";
export const USER_UPDATE_PROFILE_RESET = "USER_UPDATE_PROFILE_RESET";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";
export const USER_LIST_RESET = "USER_LIST_RESET";

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";
export const USER_DELETE_FAIL = "USER_DELETE_FAIL";

export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";
export const USER_UPDATE_RESET = "USER_UPDATE_RESET";

export const VOTER_LIST_REQUEST = "VOTER_LIST_REQUEST";
export const VOTER_LIST_SUCCESS = "VOTER_LIST_SUCCESS";
export const VOTER_LIST_FAIL = "VOTER_LIST_FAIL";

export const VOTER_POST_REQUEST = "VOTER_POST_REQUEST";
export const VOTER_POST_SUCCESS = "VOTER_POST_SUCCESS";
export const VOTER_POST_FAIL = "VOTER_POST_FAIL";

export const VOTER_YEARLY_REQUEST = "VOTER_YEARLY_REQUEST";
export const VOTER_YEARLY_SUCCESS = "VOTER_YEARLY_SUCCESS";
export const VOTER_YEARLY_FAIL = "VOTER_YEARLY_FAIL";

export const VOTER_ALL_ELECTION_REQUEST = "VOTER_ALL_ELECTION_REQUEST";
export const VOTER_ALL_ELECTION_SUCCESS = "VOTER_ALL_ELECTION_SUCCESS";
export const VOTER_ALL_ELECTION_FAIL = "VOTER_ALL_ELECTION_FAIL";
